B=dlmread('a1-driver1-log.csv',',',1,0);
A=dlmread('a1-driver2-log.csv',',',1,0);
S=mean(B(:,2));
sd=std(B(:,2));
Srange=[min(B(:,2)),max(B(:,2))];
disp('A1 1. gidariaren batazbesteko abiadura, desbiderazioa eta minimo eta maximoa');
disp(S);
disp(sd);
disp(Srange);
S1=mean(A(:,2));
sd1=std(A(:,2));
Srange1=[min(A(:,2)),max(A(:,2))];
disp('A1 2. gidariaren batazbesteko abiadura, desbiderazioa eta minimo eta maximoa');
disp(S1);
disp(sd1);
disp(Srange1);
C=dlmread('n1-driver1-log.csv',',',1,0);
D=dlmread('n1-driver2-log.csv',',',1,0);
S2=mean(C(:,2));
sd2=std(C(:,2));
Srange2=[min(C(:,2)),max(C(:,2))];
disp('N1 1. gidariaren batazbesteko abiadura, desbiderazioa eta minimo eta maximoa');
disp(S2);
disp(sd2);
disp(Srange2);
S3=mean(D(:,2));
sd3=std(D(:,2));
Srange3=[min(D(:,2)),max(D(:,2))];
disp('N1 2. gidariaren batazbesteko abiadura, desbiderazioa eta minimo eta maximoa');
disp(S3);
disp(sd3);
disp(Srange3);