file= dlmread (project-files)
file= dlmread (lproject-filesep)
file= dlmread(n1-speed-limit.csv)
file= dlmread('n1-speed-limit.csv')
file= dlmread ('project-files.zip')
file= dlmread ('project-files.zip',')
file= dlmread ('project-files.zip',',')
file= dlmread('n1-speed-limit.csv',',')
file= dlmread('n1-speed-limit.csv',';')
file= dlmread('n1-height.csv',';')
fileheightsn1= dlmread('n1-height.csv',''1,0)
fileheightsn1= dlmread('n1-height.csv',',',1,0)
fileheightsn1= dlmread('n1-driver2-log.csv',',)
fileheightsn1= dlmread('n1-driver2-log.csv',',',)
filedriver2= dlmread('n1-driver2-log.csv',',')
filedriver1= dlmread('n1-driver1-log.csv',',')
filespeedlimita1= dlmread('a1-speed-limit.csv',';')
fileheightsa1= dlmread('a1-height.csv',',',1,0)
filedriver2a1= dlmread('a1-driver2-log.csv',',')
filedriver1a1= dlmread('a1-driver1-log.csv',',')
help subplot
plot('n1-height.csv')
plot(fileheightsn1,filedriver1)
plot('fileheightsn1','filedriver1')
plot('fileheightsn1.csv','filedriver1.csv')
plot('fileheightsn1.csv';'filedriver1.csv')
plot('fileheightsn1';'filedriver1')
plot('fileheightsn1,filedriver1')
help plot
plot(1:length(fileheightsn1), fileheightsn1(:,1), 1:length(fileheightsn1), fileheightsn1(:,2))
plot(1:length(fileheightsn1), fileheightsn1(:,1), 1:length(fileheightsn1), fileheightsn1(:,2), 1:lenght(filedrivern1), filedrivern1(:,1), 1:lenght(filedrivern1), filedrivern1(:.2))
plot(1:length(fileheightsn1), fileheightsn1(:,1), 1:length(fileheightsn1), fileheightsn1(:,2); 1:lenght(filedrivern1), filedrivern1(:,1), 1:lenght(filedrivern1), filedrivern1(:.2))
plot(1:length(fileheightsn1), fileheightsn1(:,1), 1:length(fileheightsn1), fileheightsn1(:,2): 1:lenght(filedrivern1), filedrivern1(:,1), 1:lenght(filedrivern1), filedrivern1(:.2))
plot(1:length(fileheightsn1), fileheightsn1(:,1), 1:length(fileheightsn1), fileheightsn1(:,2): 1:lenght(filedriver1), filedriver1(:,1), 1:lenght(filedriver1), filedriver1(:.2))
plot=(filedriver1(;1), fileheightsn1(;1))
plot=(filedriver1( ;1), fileheightsn1( ;1))
plot = (filedriver1( ;1); fileheightsn1( ;1))
plot = (filedriver1( ;1):fileheightsn1( ;1))
plot = (filedriver1( ;1): fileheightsn1( ;1))
plot = (filedriver1(:,1): fileheightsn1(:,1))
%-- 21/11/2017 16:24 --%
plot = (filedriver1(:,1): fileheightsn1(:,1))
filedriver1= dlmread('n1-driver1-log.csv',',')
fileheightsn1= dlmread('n1-height.csv',',',1,0)
plot = (filedriver1(:,1): fileheightsn1(:,1))
plot = (filedriver1(:,1): fileheightsn1(:,2))
plot = (filedriver1(1:,1): fileheightsn1(2:,2))
plot = (filedriver1(1:1): fileheightsn1(2:2))
plot = (filedriver1(1:1),fileheightsn1(2:2))
plot = (filedriver1(1:1), fileheightsn1(2:2))
plot = (filedriver1(:,1), fileheightsn1(:,1))
plot (filedriver1(:,1), fileheightsn1(:,1))
plot (filedriver1(:,1): fileheightsn1(:,1))
plot(filedriver1(:,1): fileheightsn1(:,1))
plot(filedriver1(:,1); fileheightsn1(:,1))
plot('filedriver1(:,1)'; 'fileheightsn1(:,2)')
plot('filedriver1(:,1)': 'fileheightsn1(:,2)')
plot('filedriver1(:,1)','fileheightsn1(:,2)')
plot('filedriver1(:,1)','fileheightsn1(:,1)')
plot(filedriver1, fileheightsn1)
plot(filedriver1.csv , fileheightsn1.csv)
plot(filedriver1 , fileheightsn1)
filedriver1
plot(filedriver1(:,1), filedriver1(:,2))
plot(filedriver1(:1), filedriver1(:2))
plot(filedriver1(:,1),filedriver1(:,2))
plot(filedriver1(:,1),(:,2))
plot(filedriver1(:,1,2))
plot(1:lenght(filedriver1), filedriver1(:,1), 1:lenght(filedriver1), filedriver1(:,2))
plot(1:length(filedriver1), filedriver1(:,1), 1:length(filedriver1), filedriver1(:,2))
x= filedriver1(:,1)
y=filedriver1(:,2)
plot(x,y)
fileheightsn1= dlmread('n1-height.csv',',',1,0)
x= fileheightsn1 (:,3)
y= fileheightsn1 (:,4)
plot(x,y)
x= fileheightsn1 (:,3)
y= fileheightsn1 (:,4)
plot(x,y)
length(x)
length(y)
plot(x,y)
clear
clc
fileheightsn1= dlmread('n1-height.csv',',',1,0)
x= fileheightsn1 (:,3)
y= fileheightsn1 (:,4)
plot(x,y)
plot(y,x)