for
M=dlmread('a1-height.csv',',',1,0);
d=M(:,4);
h=M(:,3);
N=('n1-height.csv.csv',',',1,0);
dist=N(:,4);
alt=N(:,3);
subplot(1,2,1);
hold on;
plot(d,h,'r');
plot(dist,alt,'g');
title('distancia respecto de altura');
xlabel('distancia');
ylabel('altura');
X=dlmread('a1-height.csv',',',1,0);
latitud=X(:,1);
longitud=X(:,2);
Y=dlmread('n1-height.csv',',',1,0);
lat=Y(:,1);
long=Y(:,2);
subplot(1,2,2);
hold on;
plot(longitud,latitud,'r');
plot(long,lat,'g');
title('longitud respecto de latitud');
xlabel('longitud');
ylabel('latitud');
fprintf('Ruta: %s\n', M);
Media=mean(h);
fprintf('Altura media: %.2f\n',Media);
desviacion=std(h);
fprintf('sd: %.2f)\n',desviacion);
Min=min(h);
Max=max(h);
fprintf('Rango de alturas: [%.sf , %.2f]\n\n',Min,Max); 
fprintf('Ruta: %s\n', N);
Media=mean(alt);
fprintf('Altura media: %.2f\n',Media);
desviacion=std(alt);
fprintf('sd: %.2f)\n',desviacion);
Min=min(alt);
Max=max(alt);
fprintf('Rango de alturas: [%.sf , %.2f]\n\n',Min,Max); 
end