M=dlmread('a1-driver1-log.csv',',',0,0);
distancia=M(:,1);
velocidad=M(:,2);
N=dlmread('n1-driver1-log',',',0,0);
d=N(:,1);
v=N(:,2);
subplot(1,2,1);
hold on;
plot(distancia,velocidad,'y');
plot(d,v,'b');
title('distancia respecto de velocidad');
xlabel('distancia');
ylabel('velocidad');
X=dlmread('a1-driver2-log.csv',',',0,0);
dis=X(:,1);
vel=X(:,2);
Y=dlmread('n1-driver2-log',',',0,0);
dist=Y(:,1);
velo=Y(:,2);
subplot(1,2,2);
hold on;
plot(dis,vel,'y');
plot(dist,velo,'b');
title('distancia respecto de velocidad');
xlabel('distancia');
ylabel('velocidad');
fprintf('Ruta: %s\n', M);
Media=mean(v);
fprintf('Velocidad media: %.2f\n',Media);
desviacion=std(v);
fprintf('sd: %.2f)\n',desviacion);
Min=min(v);
Max=max(v);
fprintf('Rango de velocidades: [%.sf , %.2f]\n\n',Min,Max); 
fprintf('Ruta: %s\n', N);
Media=mean(velocidad);
fprintf('Velocidad media: %.2f\n',Media);
desviacion=std(velocidad);
fprintf('sd: %.2f)\n',desviacion);
Min=min(velocidad);
Max=max(velocidad);
fprintf('Rango de velocidades: [%.sf , %.2f]\n\n',Min,Max);
fprintf('Ruta: %s\n', X);
Media=mean(vel);
fprintf('Velocidad media: %.2f\n',Media);
desviacion=std(vel);
fprintf('sd: %.2f)\n',desviacion);
Min=min(vel);
Max=max(vel);
fprintf('Rango de velocidades: [%.sf , %.2f]\n\n',Min,Max);
fprintf('Ruta: %s\n', Y);
Media=mean(velo);
fprintf('Velocidad media: %.2f\n',Media);
desviacion=std(velo);
fprintf('sd: %.2f)\n',desviacion);
Min=min(velo);
Max=max(velo);
fprintf('Rango de velocidades: [%.sf , %.2f]\n\n',Min,Max);