M=dlmread('a1-height.csv',',',1,0);
distancia=M(:,4);
h=M(:,3);
N=dlmread('n1-height.csv',',',1,0);
d=N(:,4);
altura=N(:,3);
subplot(1,2,1);
hold on;
plot(distancia,h,'r');
plot(d,altura,'g');
title('distancia respecto de altura');
xlabel('distancia');
ylabel('altura');
X=dlmread('a1-height.csv',',',1,0);
latitud=X(:,1);
longitud=X(:,2);
Y=dlmread('n1-height.csv',',',1,0);
lat=Y(:,1);
long=Y(:,2);
subplot(1,2,2);
hold on;
plot(longitud,latitud,'r');
plot(long,lat,'g');
title('longitud respecto de latitud');
xlabel('longitud');
ylabel('latitud');